"""Add is_writer_applicant column to User model

Revision ID: 2321a802eb19
Revises: dec967ddacca
Create Date: 2024-11-13 12:41:55.258723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2321a802eb19'
down_revision = 'dec967ddacca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_writer_applicant', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_writer_applicant')

    # ### end Alembic commands ###
